version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nola_otel_demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nola_otel_demo_db -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  queue:
    image: softwaremill/elasticmq-native:latest
    container_name: queue
    hostname: queue
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - "./elasticmq.conf:/opt/elasticmq.conf:ro"
  
  server:
    build: server/
    image: server
    container_name: server
    restart: always
    ports:
      - "80:80"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_DB: nola_otel_demo_db
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otel-collector:4317
      SQS_REGION: us-west-2
      SQS_BASE_ENDPOINT: http://queue:9324
      SQS_READ_QUEUE_NAME: math-result-queue
      SQS_WRITE_QUEUE_NAME: math-queue
    depends_on:
      db:
        condition: service_healthy

  calc:
    build: calculator/
    image: calc
    container_name: calc
    restart: always
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otel-collector:4317
      SQS_REGION: us-west-2
      SQS_BASE_ENDPOINT: http://queue:9324
      SQS_READ_QUEUE_NAME: math-queue
      SQS_WRITE_QUEUE_NAME: math-result-queue

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    hostname: otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    container_name: tempo
    hostname: tempo
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana 
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"