// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Calculation struct {
	ID         uuid.UUID          `json:"id"`
	Student    string             `json:"student"`
	Expression string             `json:"expression"`
	Result     pgtype.Float8      `json:"result"`
	Created    time.Time          `json:"created"`
	Completed  pgtype.Timestamptz `json:"completed"`
}
