// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateCalculation(ctx context.Context, arg CreateCalculationParams) (Calculation, error)
	UpdateCalculation(ctx context.Context, arg UpdateCalculationParams) (Calculation, error)
}

var _ Querier = (*Queries)(nil)
