// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCalculation(ctx context.Context, arg CreateCalculationParams) (uuid.UUID, error)
	GetCalculation(ctx context.Context, id uuid.UUID) (Calculation, error)
	UpdateCalculation(ctx context.Context, arg UpdateCalculationParams) (Calculation, error)
}

var _ Querier = (*Queries)(nil)
